### ISSUE TITLE
Question about Amplitude Modulation Spectrogram

### ISSUE THREAD

**Issue by miguelfs** [fgnt/paderbox#46]
Hi, folks.

I'm researching about modulation spectrogram. I've read a bunch of articles and past implementations in Matlab, then I'm trying to code one right now in Python.

I found this repository of yours, as well as an IEEE [article](http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=5947602) from your lab describing it. The article is really helpful.

I would like to know if there's any reason about removing it from your repository. It was added in [this](https://github.com/fgnt/paderbox/commit/9d723795e520e024368cc4ceecbd802d5c0bcbe3#diff-c794b0530c22a5b3cbd39b76755ebf2e1ebc5ddba347915089262d1d92c810b0) commit, but then removed and declared obsolete in [this](https://github.com/fgnt/paderbox/commit/ce3ee2a3baa280e997d9c4a6d0e30d63d0ecaf80) one.

Thanks in advance :)

**Comment by jensheit** [comment]
Hi,
thank you for following our work. First of all the article you have linked is not a publication of our group but of the talented people in Oldenburg, Germany.

To your question, we have removed this transformation during the upload to Github because neither me nor my colleagues are using this particular feature anymore so that we could not guarantee that it is working the way it was intended.

Hope this answered your question.

**Comment by miguelfs** [comment]
@jensheit, thanks for the info!
